#ifndef PMTPulse_hh
#define PMTPulse_hh

#include "globals.hh"
#include <vector>



// PMTPulse class

// Every detected photon produces a hit in the PMT (with ID and time, as defined in the PMTHit class); but PMTs don't measure single photons, but pulses generated by multiple photons that arrive almost at the same time
// I want to group the photons that arrive in a certain time window, then save the ID of the hitted PMT with the number of photons of the pulse and the time
// This allows me also to study the coincidences, since I can find the active PMTs for each event and inspect if there are coincidences or not


namespace RUT
{


class PMTPulse
{
	public:	    
		PMTPulse(G4int id, G4double t, G4int n = 1)	// Constructor
    {
    	fpmtID = id;
    	ftime = t;
    	fnPhotons = n;
    }    
		//~PMTPulse() { override;};
		
		// Getter
    G4int GetPMTID()  { return fpmtID; }
    G4double GetTime()  { return ftime; }
    G4int GetNPhotons() { return fnPhotons; }
    
    // Setter
    void SetPMTID(G4int id) { fpmtID = id; }
    void SetTime(G4double t) { ftime = t; }
    void SetNPhotons(G4int n) { fnPhotons = n; }
	
	private:
		G4int fpmtID;           // PMT ID
    G4double ftime;         // Time first photon
    G4int fnPhotons;        // Number of photons in the pulse
	
};

}

#endif


